/** Domain models for data produced by scripts/fetch-data.mjs (public/data/*.json). */

export type WowRole = 'Tank' | 'Heal' | 'Melee' | 'Ranged';

export type Difficulty = 'normal' | 'heroic' | 'mythic';

/** One equipped gear slot, keyed by Raider.IO slot names (head, back, finger1, mainhand, ...). */
export interface GearSlot {
  ilvl: number;
  enchantId: number | null;
  gems: number[];
}

export interface CharacterGear {
  ilvlEquipped: number;
  slots: Record<string, GearSlot>;
  updatedAt: string | null;
}

export interface RosterCharacter {
  id: number;
  name: string;
  realm: string;
  class: string;
  role: WowRole;
  rank: string;
  status: string;
  note: string | null;
  gear: CharacterGear | null;
}

export interface RosterFile {
  characters: RosterCharacter[];
}

/** One droptimizer wish (a character wants an item, with the simmed gain). */
export interface WishUpgrade {
  characterId: number;
  itemId: number;
  itemName: string;
  slot: string;
  instanceId: number;
  encounter: string;
  difficulty: Difficulty;
  spec: string;
  wishlistName: string;
  wishlistWeight: number;
  /** Simmed DPS gain in percent (e.g. 1.25 = +1.25%). */
  percentage: number;
  absolute: number | null;
  updatedAt: string | null;
  manuallyEdited: boolean;
  comment: string | null;
}

export interface EncounterItem {
  id: number;
  name: string;
  slot: string;
}

export interface EncounterInfo {
  name: string;
  items: EncounterItem[];
}

export interface InstanceInfo {
  id: number;
  name: string;
  encounters: EncounterInfo[];
}

export interface WishlistsFile {
  instances: InstanceInfo[];
  upgrades: WishUpgrade[];
}

export interface LootAward {
  id: number;
  itemId: number;
  name: string;
  icon: string | null;
  slot: string;
  characterId: number;
  awardedAt: string;
  difficulty: string;
  /** Response type name from RCLootCouncil (e.g. "Main", "Minor", "Offspec"). */
  response: string | null;
  /** Excluded responses (offspec/transmog) don't count towards recent loot. */
  excluded: boolean;
  discarded: boolean;
  note: string | null;
}

export interface LootHistoryFile {
  seasonId: number | null;
  items: LootAward[];
}

export interface AttendanceEntry {
  characterId: number;
  name: string;
  attendedPercentage: number;
}

export interface AttendanceFile {
  startDate: string | null;
  endDate: string | null;
  characters: AttendanceEntry[];
}

export interface DataMeta {
  fetchedAt: string;
  /** True for the committed demo dataset generated by scripts/generate-sample-data.mjs. */
  sample: boolean;
  team: {
    name: string;
    guildName: string;
    url: string | null;
    region: string;
  } | null;
  season: string | null;
}

/** Per-character manual overrides maintained by the loot council (stored in localStorage). */
export interface CharacterOverride {
  /** Manual enchant/gem score 0..10; null → derive from gear. */
  enchantScore?: number | null;
  /** Manual activity status; null → derive from attendance. */
  activity?: 'regular' | 'casual' | null;
}
